apiVersion: ENC[AES256_GCM,data:7dE=,iv:0Jf9Dv+Wx669LLMP5QCrx+F9QN6pwzQ+vtH1l98vysc=,tag:hyA/ccHO38oITNRv83UmZQ==,type:str]
kind: ENC[AES256_GCM,data:MBjRRh/O,iv:8aTX6bbvKkl1uyCC7kUUySXD9LyfytWv7J7jjTYrO+o=,tag:U0VYq1calSSgb5xYBSiRKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Xdj1jTibgXBjnug7YghGX2QIrw==,iv:eMc2mZMe3x/KKMfkGGSeByo8BExChGMvYGAgLGapAaY=,tag:m4fFHsXSvJXMGIPFbdajKQ==,type:str]
    namespace: ENC[AES256_GCM,data:xeck9FF8Db+xSA==,iv:ZwVse0RPpwhXXHWclZr4efd0yXjqBeVRWP0Um3pS1YM=,tag:8gpj5DBjKoDASmQnwIcFnw==,type:str]
type: ENC[AES256_GCM,data:tke8WNYR,iv:9p1xuUq831YeyDqo3W3IJxoXAWBgsFBuSURvNH8URbM=,tag:BIT0IVa1Pv5hupGqqs6Byg==,type:str]
stringData:
    host: ENC[AES256_GCM,data:dfooPvV2TBoIa3HvqTDkHktSI4JWgNmDkokI5VImJfRSYCsiKrn/,iv:9BcnMFjLTOMANUi9HbqgvoHbvjUWF49bA//uA9e+I5Y=,tag:0Jp/LARhYvpC8Bof9v5YoA==,type:str]
    port: ENC[AES256_GCM,data:MjQ7JQ==,iv:+GPPZE4U4SOgA7g1dkZ/OTggeMKW8P3nX367fgd/NN8=,tag:CTRwnUOxVKW62nAF914PIA==,type:str]
    user: ENC[AES256_GCM,data:r9/F3HFErgk=,iv:pnllM09kkGdSjFbFhdy0DTqBlwvOSPoT20OFZOGJSWw=,tag:MPUxq4Rb3nD3Pl81ziv94A==,type:str]
    database: ENC[AES256_GCM,data:BBf976JIdvo=,iv:gYDuYYfTaYqPz6D2GILMoI1kNxZYa/8+6u+2JGHj60Q=,tag:dCc50Z/mHkDvVExwdESWgw==,type:str]
    password: ENC[AES256_GCM,data:3Njtqul/MDJwDupw,iv:jcNBYzeNuwmmE76+2JX4A/0h/3AgB9kWLtVMQY5m7M0=,tag:bg8wc7Hjf89RMeshW6jBJA==,type:str]
    userpassword: ENC[AES256_GCM,data:Inq3x3SuxJitope6,iv:nT6IWs2/A4/PVARjK+HOFH5dTcF35Rbgbd3Y50DRwr0=,tag:cj8WlMdcFQ67dY6DYJzYZw==,type:str]
sops:
    lastmodified: "2026-05-03T18:42:24Z"
    mac: ENC[AES256_GCM,data:5I8Gh6ssqrM/n7Kh9ExAXQh9Q2C94+3RF2bvSZSfbrht023j8uO4VJ1MAFcmRq288FdgH1+HN7NUe+rKGO9zIqS5uSdc+IPftC92ONfyR3vdIWt+Ac2K0+EV4Hc2kBozXr6wW11KTFEsWl9kD9NMR/H+KMlmHt2TxbBEfFDjl7c=,iv:1O3uNRVsqlH6WM3zH8oMuSPIhb//uMuT+FpfazXCjPI=,tag:1NYZ5HiUrIFQIUuvWSCJag==,type:str]
    pgp:
        - created_at: "2026-05-03T18:42:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ//YSwjOWqcVOOzOXFdx4YfxIq/NaRn43dHyXWu/WthHlch
            ZWPwFVG7IH79a8J9czVw0e0NTLjR5sR/ndJziDA+UhR2wjwEa7KJl1wIHXdk087s
            KZH9uv9cwSn3zkou+WXjja2pqoz9ZAm+WWaUX9IErL43UAQ2V5GzsF3EAIaGCO5/
            yDlfQ3Wf6SFOtzQwshRK+E7CAQLUmv9D8pjrg8UrAU3rqziU0USOg1GBP3cHevc+
            9aIKeq2XXJqnH2yfa8OQ5a+QSxGNanfisqHssRl19hnUaeJESNhvGpeo9P/o59il
            O2Hty2mWNFJ12fkYWAuxdgUbtoCbMW0xu0d62qX4MBymma8T5w2H/aCGsmm1/g1V
            uYGkgUYaivou3vZA3rYiLpL0jc5GGzw7E5zgqEJ9iDzoloUYK50EtzSV43GeklZM
            N1gS2BFqqpjKlmA5rpuQeZzdCu3TdtD1IRGINZo4YEITCLtKh5E7isebF+q42/tg
            NQL8kCaBAUEKxghJKEsV3gQf2v3qH88sbXnNEjVcdI9XMC5s0aVHyRag2Tu333lq
            SJnneRgqe3pcmz9Qg0AtcBZ5W5jL+MX+7Bs9v4uOBmuBlbwFtGLZ9I/VG2IhfPUl
            nRZHviQ5gjuWnR3DmmCn0JRTv1hIUZWu28NByLe2rlleAOBvxEIMWTkn0vzeVtjU
            aAEJAhCdDw83hGkrCxFAohvC36oawiBX+wYNi8snAjcMfEcIWHxRYQRDKk5CVqzw
            Xjk1GGnJuaWjR9sHY2MnRk/NRSb8K7hdAoy1QWoJUSn373xP7AiW1yQrcvRgjaXA
            8nj6LL6+ma9O
            =m0/U
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
