apiVersion: ENC[AES256_GCM,data:bFM=,iv:uOWj3KU/5hakE1aWjagHYKzTesK3M83jQF3dfEBSY38=,tag:gBzA0HTsGADWzUWviYlVtw==,type:str]
kind: ENC[AES256_GCM,data:eRbGfYCe,iv:XRzLRNrQL9zo1NkCLS5peDv4Zg2ClqnVUKn++fZvnGM=,tag:4xspciSYPiKnintrk6h50Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OKGW4o38tDtt8NfNqqrUsRNF,iv:d830JVZZfteTCRCrlmtG+tX15K+htvV7/AYuCYUR7mc=,tag:HZjnkj8di1kxVA/bYFETRQ==,type:str]
    namespace: ENC[AES256_GCM,data:fwG9cUEbBpQ=,iv:JTQZY89Saj83GuNx38ivHrUAFJy877IuODzekHJ2Hqw=,tag:3VUT99W6pMIXBZmcBHM7SQ==,type:str]
stringData:
    postgresPassword: ENC[AES256_GCM,data:B1bmzWJj2/AelqOw,iv:Jhs9ZgQodKqc/N9nf57A3rakTbSbKEM+EJ3785vkrWk=,tag:+NrN5zg3RO+FHIyZLEO8LQ==,type:str]
    replicationPassword: ENC[AES256_GCM,data:JuDhuMJU0ZjLvyCo,iv:NfuXUe9qYED0oNB4I66T8tYgH7KcYJaQFxxsZTcfQuE=,tag:17I9VwvjVLEPBM8D100mCQ==,type:str]
sops:
    lastmodified: "2026-05-03T18:35:46Z"
    mac: ENC[AES256_GCM,data:QVBublvWtgcAch8IH+1B+Lgjief2VQQ+weAk1cs6+mLPD7WU41hACeTjC4DPu581cKd/8PyehYOeHd+o8Vy1YuDhOK1nDKF/AztqyPuwMvyrtuchG5FbbiZqWvu9XB4ddML/hXLQhL8md+fWsnwoC6uRfsEFlNCsnWnrE/rC1GY=,iv:ATcggV0BtGbAfrFXhaeruHoilN0P4b76SLmcm0+rSrw=,tag:cfayq4E+QU4lnsB6eXwHxg==,type:str]
    pgp:
        - created_at: "2026-05-03T18:35:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ/9FrFkBXKbm9GTlXjvmJyzVjFgMKez+6/D35fSvFTWJyyX
            mHWIIdNQrvohoo72pnGf7KKaqEIxBbGR5sOL2k3lWHk993oWLY/P+X6qrDE5vx3n
            7KV+xxUpsLJWBPbPd8+6Gnumxg04q4nbV4jvt8h8AQ/+CJZEomJWpyqFabXIUs1t
            rAiY9vl2QlHtvsz01nEh+aBRNBElIfyG4Ed+kMW5yCwMUg8SUB+N6GnN8nMIi8Ub
            KpyRxSbtvE9ycucIuixaqxUe7F4+JUL5rNuB27cZ9x/nUw/9tCScB08enk3o2KUW
            a0YAqQDuYN+p65dKXYyLSOPXHy8gGtPZcvoPhcZBOXUxk9mSQbXrjvPYzMeai4TH
            udQupHOONaCg3zqjmIuU6kFvnvobeRs8Me+mvK2A/73QzuGDuO0/b5NI47ETWYuP
            zIcoScEWjY1P8g9KUqHcYsUQytorh8w1CkcFkNwH/0fBZM1MhLBm/BrlGs4pVUtN
            UJ8YPUJCVu7tMghSrgiSqAp2XmtTk9+KK8WFcLNSrXXbLYxYwtNItFYNz0YRaEDo
            zn6wZgT04lZhP5TMq2LmZ5B9ju2gVa4XO6vFmK2zzPtB66j4cnx/7fngw38xBY+Q
            WkwWUG285V9RFZW6qJEP/Ek8E4ooHutxkAk3v9gMdqzN+aWtiq8160/DQQJgiLPU
            ZgEJAhBegocNRR6S+Imqgbf3FyQRF1nRr7PPiefWsA0gmrxSqbowJLb/0iwQhMcz
            S4omz67NaB0j+JmbsMgx6Hux9eYnhS4RVTbf8N26I1QHcD8D5seKUj8H4K/4Njmh
            i8MqSsHx2w==
            =UyCk
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
