apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foreman.fullname" . }}-config
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "foreman.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_HOST: {{ .Values.postgresql.global.postgresql.auth.postgresqlHost | b64enc | quote }}
  POSTGRES_DATABASE: {{ .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresql.global.postgresql.auth.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.global.postgresql.auth.postgresPassword | b64enc | quote }}
  REDIS_URL: {{ include "foreman.redisUrl" . | b64enc | quote }}
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
