# loki-stack helm-chart deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  syncPolicy:
    automated:
      selfHeal: true
  sources:
  - targetRevision: 'main'
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/homelab-infra
    ref: myRepo
  - chart: loki-stack
    # version number from: helm search repo grafana
    targetRevision: '^2.9.11'
    repoURL: https://grafana.github.io/helm-charts
    helm:
      releaseName: loki
      valueFiles:
        - $myRepo/infrastructure/loki-stack/loki-stack-values.yaml