
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: nextcloud
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: apps
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: foreman
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: llm
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: puppet
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: postgresql
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: jenkins
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: homeassistant
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: mimir
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: loki
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: keycloak
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: database
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: registry
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: proxy
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: pihole
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: keda
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: runners
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: networkpolicies
