apiVersion: ENC[AES256_GCM,data:tE8=,iv:m/wbLokm9+aiO6ecEkkrg+GfIwoA9obP3fsvicA506E=,tag:wXUY0+/rAh2/c4q02NB/BA==,type:str]
kind: ENC[AES256_GCM,data:LKKFwtt3,iv:00zieFO9U9pSmud4q9Y4MlQ6W0v79UpfiGCBEMppX+0=,tag:q44EOdzRUR39gjU7VAjZ4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7IS6/B3gB0Co+1BtkEEM,iv:0QDhoMs6B5lqTl7YzNbEd62xs8UuvWD/cuZFCSvmbC4=,tag:y/CqKoXEAq4gNjb5ygRC9A==,type:str]
    namespace: ENC[AES256_GCM,data:IlWHmuPqpzvABA==,iv:WMM1BTmtjldFhxntxOnQIiINa2t7Io9bHEYER+OfGpU=,tag:iNaB689q9AjgBgDmW8N6oA==,type:str]
stringData:
    adminPassword: ENC[AES256_GCM,data:jSM7CV5GqTuBqOi9,iv:1JqQAenmGfB8ClcABGMrs04zb7wk8ntMofj9wTERCjQ=,tag:WJYpCzpf7J6qzcuqD7UbMQ==,type:str]
    adminUser: ENC[AES256_GCM,data:9dfgsKaZcvg/Kmuh,iv:TEQmYREkNBS8W7zFFkt/ha2BCBl/FS/zOLJrUDFPWBI=,tag:7IKQXoDYQWoDyYtWh7NNmw==,type:str]
sops:
    lastmodified: "2026-05-03T18:35:46Z"
    mac: ENC[AES256_GCM,data:6fss3AHVINjwhbCtdGLxOkN5WsFs8Q0AxujV8+ojhrr2wQhK7RFrJzUaFATSyQNn9dZ8MH/6n69xyddIrIkPm6YyGDaoDKwmYeBQLtkzj51l4kbqxfctCHqZLoysv8nOd8aynyXScBXKuuJ7s7J2fCZ2slBsf9UVJej4NqceK6o=,iv:TS5ZdpbBwndS9UIgv6f0Kjxf4pYfRE9OST3zOCCcaFY=,tag:ZDlnbXHRr6tfi1dkp0g4Ng==,type:str]
    pgp:
        - created_at: "2026-05-03T18:35:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ/9FTQ2rGKyMYu8w/hel8J2K8NeBmyJXm16Wfr6AFCxBDow
            J6+txQIWdsbv9g9MWiMbeSsd0ONeX2sW79WK9rvSN+FbwaFiGT2cbULEm0a/FM0C
            UZwlthmTYsKGMsYYmts2hcKKhIC+uf03SyL+FUvstgQ/Pi/V7kroExHWHhRSMiGZ
            y4PZ9wqZlh5DPO25zX2m+8cajx/jxdhCdsjDCpz8xVtFgn2BL/R6QqupLF8y7nj9
            QQhy65ay08OgqRpFbe2S9A/PxergEtEjBn7/iIwyR8vu5R9zZjpHvai8+S24/jC8
            rX04qeRHHrtSgJuifVvAZdjRGz0wCoV3N6es2brs5/s+XZh+ZuhWKFhzUgeyqOYR
            2Aqcu+7evSHatPU/wSydWaAd4YBXeB64MNGF2+5na0WsUJdMMnJYR5JLekg+2AN7
            oUEHVWph1RiRiN5+wb3vbrblP585EyPQUXsve5XfrN0YSJCEZIkwYvWA81quRtu5
            uydPjkd5FREAUgLlH9So7Vl+1VrEYVU1qBJdQOJai2iFds7cSPCt6jWlL6ylIrfJ
            xr3CRfIKMXTbKg9QrImzRWJzeljm1qPzNm3JLXRjfi9fGJxF/zv0rFXOS5Vy2LnS
            qrr5Yp6gLpsNbDNZlMm3CXZTe69Oe4dB5e76qmFDiCZ4Ae8Wg6jxA6/YSuYItX/U
            aAEJAhD2p2cYnMzmw1F29A9yKnd2LZIPNP92F3JUgURRUTzh21NwzUukrUijovD/
            z7AtJZi9xxebS2PQi27rQdANhXWXW6GwDXThdAPkl7yMDSk8vHhDJLoUmdYwoB5P
            oLwfAPYTkwNP
            =hopu
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
