apiVersion: ENC[AES256_GCM,data:bso=,iv:4nD7vQ0nExRExqvJ8N6Pa4CrlSgbjm5Aa66CwPx7mmw=,tag:EDGRXDPWwSRT7cWEo6Pkrg==,type:str]
kind: ENC[AES256_GCM,data:LZvaEGZX,iv:HD/7MWz31wpUgko+srwKyqMMOnnJ3vvVHHMWS0QVSE0=,tag:RF11+eebSgMp26QaT43ykA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UwyG3py8txhHNjA=,iv:oNvpK1H9dAK228J6HpPMNXyZYR71mAOAJTWpZa1gvQ8=,tag:248Gv03SKkewII+/EMa0Lw==,type:str]
    namespace: ENC[AES256_GCM,data:UgWhgp0=,iv:2xrsuL0vYAAMamWGlFULh8ARDmm9cnEddgw1ONrVqxQ=,tag:VOqC1PI32OIgjxLiasrBBw==,type:str]
type: ENC[AES256_GCM,data:qBvJasG5kn83mLndOpiAQHk=,iv:HizgtiXKMOlJDPbl6kN6waHBV55aUw92rHRtheoc5fo=,tag:cTRGGtgHwHrvij6UuJ2qjw==,type:str]
stringData:
    tls.crt: ENC[AES256_GCM,data:xBsvvwtXgnV/3ODn,iv:Tc65g+xlmyEZNbjbBeyGaS95HqlMqdgYawKW4RcnMjU=,tag:/2lslBMQOx3UWfdHWeqHvA==,type:str]
    tls.key: ENC[AES256_GCM,data:KCH6r30+Bp0qxsRp,iv:S88Mw0d8GovAGRM+7vQM3ZrK5HKvcdacUANfa+9RkoM=,tag:My4KxA1+KEH5erfiUoLnyg==,type:str]
sops:
    lastmodified: "2026-05-03T18:42:24Z"
    mac: ENC[AES256_GCM,data:J0JQz0aG5FSQAmNdf0nAmKlOtG/0JGwdJYcK6o4ez8vbelB3/JAf5S2tuTnKQdxsLVIM9tqjeCrBX7ICukSW2z9IlSn+N1+uGPCIiw84t4vCYelp4HX8iwTUOXCS9wVZvxd7DvokARxFuygKmQzQpxxJ+0qzchIooBGhKHvwPsA=,iv:Gg40ZMC+uQcO/7Cin6VrwYl9EMWAP/yO7HMN7Z/d2N8=,tag:z4X6b02nQ4jWeHXIG+70dA==,type:str]
    pgp:
        - created_at: "2026-05-03T18:42:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ/+PYZeNnrA6zZANnoR4hSQj3hMAHbhchL/DgLa6ooztuHQ
            ysBxm+rAobO9w0gHz4jzb31RoPxrOhEE4nZyaPWElm9zM9D4z+33fixgNDlLoU6W
            D/aDRIhCvngAuynkYaW8UvCTwctPahkQazeaK+KnnScEf/DCHLjokGCnjofrGNAE
            T2Q9MdebckYYP6H527SA53hIk6GjLO+Zj3+hXZxd243M+2DJOL3ok1OfOOQYOu5Y
            WJ6qpotZeG2Af3idEgoXPr1671P0ltqtLPFDh1IqmNXqT6NB/rW+izX87uFZrXJi
            4KYsoci28dORuY9SshIAdq6ID6fVD+Af/JdpTP5SeSbTaqTRYoImFDdwktpDJPWz
            A3UsGeHzUgQBW0t8xTk0+OhUDDryU9o+eoR1L8WSoBlJ8wJghrGTerL2FARjm0VP
            y3FDiTz9fp9w/TEUIDL8kpUHt5B14chraJ4lMc40iIGvbzevMgsPy4Mp29DVBzOT
            DojribPm0vAN4B9HNT+7wc1+fTnu7fqFUmm3bkkFehpSZkO/bMkFvJa7qbNkPaiX
            KFfNuVBa8QxFek7Nv+pnBeKFX15wsfFxdRiuHt7/tHPBrmI1pyAHIATZI6whdnBi
            jyDnq08TN4I2w5BEgiWiZQM6tnpXBn+AywOsSKAfv7N7rx3xZh3X9HFg96C2lEXU
            aAEJAhDo/INhYacNcGkmdivODk4IJ9tzerffJaHVs2s8Ed9VOLwayl+nm2cXsxYQ
            LbPh1pEF4xnxadYtePl2aDDw5HOdurDBleiWudSEE25EQHiOY330/7E4jHq0FXXR
            GQ1G206vb+gQ
            =eEXb
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
