apiVersion: ENC[AES256_GCM,data:qkA=,iv:gF+o1cihp1hrVPBoS3Gle3YO4HqIffWKoIlznFm1xZQ=,tag:xtTuD6cZ+SS9wJfLplyH4Q==,type:str]
kind: ENC[AES256_GCM,data:CdYqjFrQ,iv:hje+FPzIqvSLms58B4NhtdoI5IeS7lfU1IPEFfQ8LK0=,tag:A+kdOSEllLlRdzkT/qVGug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zrDyx7jhIqDMmjZXjw==,iv:Xf3VcgNHhbs8y7lOYnowR4PScrQGptxKmpvB/MLD8G8=,tag:EuSk4tkbGMX+5LFMRBK8jw==,type:str]
    namespace: ENC[AES256_GCM,data:+OIUBkDN,iv:mZdY/JHSYcVO1OctnUD72G06XnytYA4neY4c8UJIPZo=,tag:zUJ2ECmp0gklRm6dsuMzyw==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:7lQwhshW,iv:zmWhDm5ERJv6HUVEJO2sIAmKDnEbXaiu8EiPKabzLTs=,tag:sKjc8f0y1Y/xfZO5SLtflg==,type:str]
stringData:
    admin.password: ENC[AES256_GCM,data:oiCLA4i6HD90ermX,iv:4fe/KdNjKcojR/oklH1DXduLhuRIb8nfVxIdp1+A5h8=,tag:Jiyb9oK/SSfCZ+ox5XV7FQ==,type:str]
    server.secretkey: ENC[AES256_GCM,data:c9Zj0j2CvBvTv8kQ,iv:sylRSUgPcrbMTGrB7ldQz4xcT4HzHC4PdwG9glkRhm0=,tag:1rDTFWfjFJgkGS34FTy7oA==,type:str]
sops:
    lastmodified: "2026-05-03T18:35:46Z"
    mac: ENC[AES256_GCM,data:VnDQS2Q1aLaGGFelNjk3ssm3yLZL3oiEfxoK7TORxnUwOu0bU7+/83YpOuq96H0NobHFiBuPKvqI180L0nU8DlSgi8vHzDqqsIFIKDRog8Y7CxvAfhSfo4Ef+07Bu0mE/dXhvszFdb47LO1boASkIKaQeSlElhlFIR5qGkgT0m0=,iv:Qx3sE6DLKC0AXMOJGdGto+UHKGMPWw98lsIyXjDgZ9w=,tag:vZky/Z7bC5YlxpMgkVkVfg==,type:str]
    pgp:
        - created_at: "2026-05-03T18:35:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ/+LVzLG1ztAX+MgkXCTYCVgDjnYKDuX4G0ymAyu4tCLDuj
            sJw9jfGsfjuzS0N3itFhvRMLYquoHjpm6SF2wqpCPAPc5qJVa+S+pyaOPUodOfqs
            Nf9OtT0yphq/ihdHTR8KFcuUw/1HuGsjeJzl9xQ2o1kdYoOR7nk3xuI/YwmpO+4u
            3sTu0Fm3aTfd7xN5Z7So6YwOCMcCpCinuuVkBQkLxaQ9wyPX4s1mT45TABGZBP5q
            AJH0+vCt7vo29/UDgPAL3xT/cKRZCK5EmsYsghir3q2Z59g/l6RekwH5rFmLKnk1
            lJV9L5N4RZ+teK84b7F3zc4cru60TzUieA2wKpeP+aveNtVJdrrdr1Mw+sPN1JKu
            eNemEgrUNORnmN6y1n8EHQebl+qTSQ2Ky5trxeBHhgF652yhFA8MrbMD7IwBC0cj
            aLSTSjBp5+B8ZE469wE68/qENzp8l30bnDLXnJuDBUrikCJTJfU576mp7rOUJVtB
            kJ0nGWlcOtbghG/I5WqwAvTk6SYV6SdvMhKGt8UjRvIesUqCgfFpC5pdP8OR5VxR
            s7wYi4hHxcnnpbE8Nqg1aSXlhwQLWbdphd3E9MRKI5jhvk4Z9jHuC4bBtd+DWMhf
            IBsdQgkTPX5/FnRKh0jZPKY8HVjrqJRYphut4T0WyOYLdYCmd2AYvMbbmKbXt8rU
            aAEJAhADlP9SJy72jE1CTl1/2DgYLTgjxx5MLWxFAet5ETfqMCX5FcWvyMUsKGz6
            4IvgNHjIRgB8u4wr1hFdDjU3XJIN/dORlyj8c1hDMzX0TDn7ppN1MvDftuK9SMig
            xyzrJ9c8bksG
            =uxzO
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
