# loki-stack helm-chart deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wireguard-system
  syncPolicy:
    automated:
      selfHeal: true
  sources:
  - targetRevision: 'main'
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/homelab-infra
    ref: myRepo
  - chart: tailscale-operator 
    # version number from: helm search repo grafana
    targetRevision: '^1.78.3'
    repoURL:  https://pkgs.tailscale.com/helmcharts
    helm:
      releaseName: tailscale
      valueFiles:
        - $myRepo/infrastructure/tailscale/tailscale-values.yaml