apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data-pvc
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: keycloak-data-pv
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-data-pv
  namespace: keycloak
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  claimRef:
    name: keycloak-data-pvc
    namespace: keycloak
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/data/keycloak
    server: REPLACE_WITH_NFS_SERVER
