apiVersion: ENC[AES256_GCM,data:/QU=,iv:6NNHfnUJDrujQBp1TcByJTsNYloKtmzsqG86S6XPXMI=,tag:DzwqRxDqwRmJatTdRaN8IA==,type:str]
kind: ENC[AES256_GCM,data:drwiaZAW,iv:ipVvcLCaOarElqQ6EspkqOEG5KnnLSRKxiq7507lvh0=,tag:qOBa+TwKkLp9RsjfXH238w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RduMHSWeLiAD8hkLStWlPg==,iv:6ByaWEKZUzFmSamAiMYAaHvaJxiXmbbB7+Qy6+3w9x4=,tag:iW8M5fCJcXES53oGHVBeaw==,type:str]
    namespace: ENC[AES256_GCM,data:3nyxvTCSvok=,iv:hdLyw4u+Z1Dz47YvUGmZt/ZFR8blauzzPZEH/eolE+Q=,tag:gEZrXEhOIeRG9k6kHneZkQ==,type:str]
stringData:
    adminPassword: ENC[AES256_GCM,data:eLVHItsdfkNXAdNJ,iv:+GdTl0SzGm9bb8ivOa7ZOYJlMQFRS9r7fx0zZ1HYSr4=,tag:UfDdEOKW2NDMOb6HMnGang==,type:str]
    postgresPassword: ENC[AES256_GCM,data:UMsiYKhDAKVfLAdM,iv:g+u/LrDBhyV5dOBd/S2Bzz2RDF7mp227zbLwmLUnelI=,tag:fL1KROJqRqq8Hzdcc4f7IA==,type:str]
sops:
    lastmodified: "2026-05-03T18:35:46Z"
    mac: ENC[AES256_GCM,data:t2gaVRPiDjt0JTHRVyBQKvMblaCv862z6kEWHTG6C0MU/GS+iTvT+Y60QjGy4BQozMoW6cvQYOjyb7FPyQ7z0SsiVNan5pCbAlRdSS3u5DpIIab0gRuWBhLSPzFUaETXALhufmyaSptOTMMmy/fDnUxXFmZci2Z+9Blby7XVtRQ=,iv:Z1JLAhyRpUcDyr3yeRzyMahkMNTbD56pL7pcbh4s+ZA=,tag:tSVga/F5Bc53DlE3t7/OcA==,type:str]
    pgp:
        - created_at: "2026-05-03T18:35:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7ARAAlSqO+MgBqxK2HSqPPDIQ2SXDA6aEObhIXXoB5+t7QJM3
            LPIdPgTuNYTkCOhBpXXAthmr7yRXxHckNT78IrHrgTqlJ0l2+u0W4c5/eLpBMrGr
            H0tnWhbbecTLf5uhQbSHDz4q1Qo1gJJNAdfLpoUDgsLfKG6Fy/nVYxfnFIGjUhR/
            og3O3tVJ9PXuhGSVGG3dC3Binfg9KT9ivUHUACso0I9wDcyNI6g7ps9W3uPDbLZ0
            fNJXmyGcVzOrSj0RqIq+yAD4aFRbcXyT87fGIbxSw/Xggo2v/6n5wUAt0Hm3Cp/v
            XodE32mwV2+xnBH21k100BVqJpLfO9E2QnSDQ6BGQcDVgdJdRncM7bPGDbF45isH
            MeOBEoVe8Ee4pTzsFbhS3kVifrCRAPIHWP72vvj43tlGdE3pfJv2/w6tbxj+aXRR
            RaUMdnZeMgfH8p4n1297rufM2qZX58OYPKlo/CTQfYgdLotfiT/XM4hDqTKUA1zd
            uvbNoNEDCO9aR5G5b5+n3ov0pA0VDZONbCrLAQa+Y+epILrf/Nxldt9PpRr6T99m
            vDcUrsvpcOxmKsov4YsCLBxLr/mWE07pCHB/hezU8DrZvqYHvf2e6iNoq7Ye9ZnX
            dNJUnAaJhywFtYRvmGLL0ScQiRlKcMdxJxySj6m0+WaftB9qis7UNS8czJ2rBcPU
            aAEJAhALwzbPbTBoynU5x9UtppjLH/HnWXjQbdjGzq6UhYmULmGtQs2/7prGuHXF
            WQq9yqczRvZm6POb7aW5MI3iv7mHZ+WijzFC3h19mQrxM6LzvjvmKFWT007WLL4M
            WDjumVs4FSLk
            =aC8U
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
