apiVersion: ENC[AES256_GCM,data:Dkk=,iv:5rCABrBU7ELbFHIMS4qk12T8bKhHyQceNYE7k8ikf2I=,tag:qQzsRuG6B16qTUvguZUydA==,type:str]
kind: ENC[AES256_GCM,data:6CFvhEmi,iv:ty2rhAE9UmQRzgmNaEmiXiMfxRBrKOragcOqc8FC+TI=,tag:WdBtTcyZEEx67pnAKWD5Dg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/bxinXk5tOhy2VBJGofYyCVQIA==,iv:M/YSW4ZcPa/1dXQ6V6qxcuVcturR0gV1CbjaX3gu4dE=,tag:BB8a+AuoCGEZj4KLp4JmWQ==,type:str]
    namespace: ENC[AES256_GCM,data:8llrtdobY9A=,iv:mHM/eqUvEehbA5rtgmKg9HdM50vEynbGmS6PI3U9OWQ=,tag:pg8JWi/Zpw1bvuQZ6eq7xA==,type:str]
type: ENC[AES256_GCM,data:5VsaFbTa,iv:GIsm0x1mkYxj+GBKD8oMRaJRazQxrvdH9jzvYDMq+Ws=,tag:l+9+hZWJViXHQhaxLPBnjA==,type:str]
stringData:
    host: ENC[AES256_GCM,data:VNbn5svxg6IFCzgawUHiphO8bb7pJG9NOvOC/MSMk4c66EAp0lZX,iv:7kZ1H83pJcnEW96OCUSUYc/XmYLqmWQELLEyklBgPmU=,tag:aLOmSPlCXvz1VqsLBrcO5A==,type:str]
    port: ENC[AES256_GCM,data:pF4HRg==,iv:Aah3i5cnAHlUJ9jaDk8HAIrwQGebXihyP5oT3N+PnjI=,tag:JtzmLtis0tPf6/8JPLEbQA==,type:str]
    user: ENC[AES256_GCM,data:9ODmwTK6KK4=,iv:Qg5lybHLFk8wU4GSCDY+jFhzx1TU1CZ7//f5xarAAAY=,tag:5InqJB6sKdk7vGk9E8oODQ==,type:str]
    database: ENC[AES256_GCM,data:u6uqRzp9/Ek=,iv:A1erT32ovhePJsDYxE1FU/YRaGOWYbiAmtJRhDD7zGM=,tag:EfpTvPHlTVsheQrmwzPJQg==,type:str]
    password: ENC[AES256_GCM,data:dO3oj+F0dqR3YaoN,iv:99e7rjHiENLgJ0kkF4hcRqPlAs6iSWpmxCin8sdJerI=,tag:JRLqTGlCWTQ8PTtnIn2SNw==,type:str]
    userpassword: ENC[AES256_GCM,data:T018Zo0wrIe/B65U,iv:2MIXlbMBKszYuTD8Dki4yqmLfh2EgdSbqDtZLbPAEXw=,tag:qbEQs4C+/l3KP2I8EbS8UA==,type:str]
sops:
    lastmodified: "2026-05-03T18:42:24Z"
    mac: ENC[AES256_GCM,data:FzuWtx9AMTGZVBJT24VGiJy9Qgfe/l0+SjTf0Hm/oFkT3ugrcitJivNWu4vnMtkRzWUfYehduBNR+o5G8im/eFa4NgyuD8D/zoD2thdpBubc17NBPTt1BuYb+qEa1LLEZtwLa6+MiuD/ImvkNzXur2nyuzfgbNTb+VuR8zm9BU8=,iv:mkPqVcAkV3YEJNpLN/IzuXrbAbQ1mTIs6I9YyNjrn2Y=,tag:GN2ViV1cyGGkD3ysSV3owg==,type:str]
    pgp:
        - created_at: "2026-05-03T18:42:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ//RhiVz+KMaxlYGmUf0wLiZ8fQYElSzi1GFMqxMxMVhr7/
            2VEYvv12KLnrXOaFWYe4Zs57u1qpqtTaz1ZRg38NxPGbybH/cTZabNqchiHBC0pt
            +P1S4bVXxdQes8138ynSJra4SbqGwurodoXHGM3bL1ZnvJbIvASOGg2THzMgv1z7
            oHijYY+3J7dIlihKwnseg98mAoBh32EsNsaJt8/o9+MvK7ME7NCN0O4Y/ubxpvu8
            kzpcVpDM8ueyhHKlB8+PYaD0QfX7mvBX4GL0usAmV/nHnRGlsZUcb2noVllWZKvs
            +8YemTUR3NhAqbxY5WmrpXl53cQmXE8AXibkj5UAadEBRRBIRbV+cFYdqddkoP3L
            0qAT0ofIYv/7BMt+RkypSlJDGbtw8XcC1Fp7UuFImQkqNC/7ccXs8cjwgYZWWAzV
            0R18qLCVJmDQEQ9rvdGfthlBezOkOtgpsh7PdjZ7gOO5v2NovTS/c0hh4+HlTW6t
            alKcIrSu2AbyUaxZrN9xOdQnhVAjnv6yjiA340NLrJ8xrMXl82CzzQFl+bwR9F9p
            GTR1tQaCa34p8mBPKB5bnsWdm/xu0NQTBZytEUFSIebtI5J8h5ygdtUGVzmhjjiR
            i54aNGPGdyYemh38AyUHjidu4F4J2gNgpENczkY9z9UPsyY5tjknKYR6GCxdxsTU
            aAEJAhCXInuLpriy7hG2fPUSkoDoAsir4/59h6tLxLPJXqPTmsSlVgcSZpgbVpNV
            KefJ8IRMqQoNf4ZIMtKl4XzIp++4qBQ7KTt7uOzRP6aauq5upCwzuISFJK6vyqHt
            we+CbLxUdCuP
            =Hopc
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
