# loki-stack helm-chart deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: true
  sources:
  - targetRevision: 'main'
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/homelab-infra
    ref: myRepo
  - chart: keycloak
    # version number from: helm search repo grafana
    targetRevision: '^19.3.3'
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      releaseName: keycloak
      valueFiles:
        - $myRepo/infrastructure/keycloak/keycloak-values.yaml