apiVersion: ENC[AES256_GCM,data:N4w=,iv:gwBC+LfAUyFm1xA5GhUCtZMvGzkYZtlg7JSzNKgl0M0=,tag:jOL7MmmgbShV30hvySGNBw==,type:str]
kind: ENC[AES256_GCM,data:XdpLA7+A,iv:6zXlp6Is9YtEuHuYawXWoczODH/8hwKqxtzBINEXVPk=,tag:Jl1wPimTupQc2co4fkDdRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Gtw4FdQ4tBc7BzbJSi0+HAws748=,iv:V9UlqM2RMvN2S9ih/quPnvY8Hx9YN4nNHkT4WqguaFw=,tag:/X7IARLY94CJbFsm+WdVug==,type:str]
    namespace: ENC[AES256_GCM,data:Lx8n/Vda4geQDoRW,iv:aLAffMP6q8jzl2Z0pLaZqjZn6lELx7RH/MJJc8U9zrc=,tag:7zVXiOpFlrXi7tT1Jmqdbg==,type:str]
stringData:
    apikey: ENC[AES256_GCM,data:1VaeAZ5fOPcIpVgD,iv:RJ+4sJfdChUmrtySTyr3/iVKfGvdLKuo2Zt17l6cq1Q=,tag:pmk8Ii24cYfZ1fCw9P9Rqg==,type:str]
    email: ENC[AES256_GCM,data:Hm149Ja14j2P80Q8rJYFw9LDXg==,iv:vlao/9/XURclzODDxxUPDPZZd1BM81os/H3R+cT4RCY=,tag:akf3HwXmiHWWprb5Ctx7Ng==,type:str]
sops:
    lastmodified: "2026-05-03T18:42:24Z"
    mac: ENC[AES256_GCM,data:cPvp7U8W32YO3/dkmGsIv5pYfF3oxo6NOaQ2Ft9nnklKdE71t+BMxENLL5fdPJz8gRCjAdT6hV3UDIX+hMaeq/epJ3uLhsAQpcfEkXb3Q0JtrXzMUaN5hs3TFVBfmPrWZSBc0ELuNW81A2iieGNj/rbZaREcQCtGtn/CWjQMZlw=,iv:U04y4s5QkeDgQP8p5zDPuiRMVZm01M/VEJK6GgHmFgQ=,tag:fVG51T/LU1mrmr4Oi1HU5w==,type:str]
    pgp:
        - created_at: "2026-05-03T18:42:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ//TPqaPaj6HsHZyIFYgQjGYdVoaGDVGk6IIurSZCYjWqlh
            vy4Ni21brsjOxJd6SAL2jp5fgu8ets/cpRNFuOz6az+6AogynGttxrihbFH+xmX3
            YlFlNzpv3ib3e095ZBFYSYMwFCSrL/zf2Ea+Cg7XcJ2E4BflSJtP2oxIyI0HyCBt
            p/CbH5RZiRczJt507pf0OWBMfpEa+a69VBW+R9LDNkns3gMbq4Ad0GrqS+A8GpM5
            kWoPfmu/+e9jMoaNtQYb+f7/Pb8l8WiGozfsRfvaR2AgdutDOjyo3svtqapGNZJ+
            lVncmca18dat77KJn7B45Ltkh/h+utRt9pNmKneKb2ygSP3u0cfVJa5+81w6ZCq+
            QLuz5bio+Q9w6a+CjrOKBUARbSIX3dRcGqxtR4WiEYvFp0Rrz5f/yLuaolM1ls2I
            yjp5uvUdKsI0AamwkXHMGRvu6cR77ScSzfWhFvFYCTn/PFMvsBu0N0mtZLjLCPr6
            hEtW94LN6dP6yB2zNyKGrolBKApE9PcvUPNVOMSsZuE4g+WYm+ttqalw6bPUyICn
            hE02NpC009rq9lP6ZVmG9HVVWkQbdF3Su8Pc2oCwd0/UbouenIn8zq2Zaj9+REqD
            OAD00nKiCiR6Q15+ERjlGY17N93qsJjK3eeZm3bxJIXflidSv1aag5SIzWL/qdrU
            aAEJAhB3Zn0J/yttG/Dhr4hcadtd2QKiAMEetnS8Hm2PfC7lVKP6Y0Ae5G08Aczc
            h9+F9hvBRUDF10Im6hXR5l4GL8K5VmXwwzU5bbli6pdnoG3IW30OcI3WthjNwT0D
            OBoF9sa3ENp3
            =7PqT
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:TpI=,iv:rrC4EQzcqNq9l2QUoyhT8eWiyHfw4Eo8SkCoow2TsaE=,tag:Vs/pHO1IqMCYMj6hqbgR4Q==,type:str]
kind: ENC[AES256_GCM,data:9XbTnI96,iv:87eViw4VGrJArHx1f4S6do6In4XhKZWnsct9Gqa6XOs=,tag:k/jfd4KAzC0cIrkYtWpaVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nzQ67hz/OgB99Ezqx/YyROxH,iv:OBGaIWeWAA3trRySFCUduGdDy+JFcMEKoj3V6wH1fUY=,tag:JkR+rdbt4zp1D/ktaXz7Jg==,type:str]
    namespace: ENC[AES256_GCM,data:hK3aGdPJN/MRcQlA,iv:l2OX+WIdeNo+P8ujU8JeFUBA+pA6m0g9WZtIDN51+s0=,tag:L/GTc0k4h37q3N/C+ct7rw==,type:str]
stringData:
    apikey: ENC[AES256_GCM,data:tv3GFFWneiWYwuoY,iv:l8pxkcBXK3Q/6/hpQv96EbzDup8hzilMCAvhpcMDvtw=,tag:N5ArlM7k//h8AOJN+CnyzQ==,type:str]
    email: ENC[AES256_GCM,data:n2Y7P8mn/MkdWZe6OjBDjAbCsQ==,iv:SJlKynghz3nTyufDLN7FyLcA7jmW73WKDGFskz/5yKw=,tag:PPPTvTPwIh99v9vB2GsVGw==,type:str]
sops:
    lastmodified: "2026-05-03T18:42:24Z"
    mac: ENC[AES256_GCM,data:cPvp7U8W32YO3/dkmGsIv5pYfF3oxo6NOaQ2Ft9nnklKdE71t+BMxENLL5fdPJz8gRCjAdT6hV3UDIX+hMaeq/epJ3uLhsAQpcfEkXb3Q0JtrXzMUaN5hs3TFVBfmPrWZSBc0ELuNW81A2iieGNj/rbZaREcQCtGtn/CWjQMZlw=,iv:U04y4s5QkeDgQP8p5zDPuiRMVZm01M/VEJK6GgHmFgQ=,tag:fVG51T/LU1mrmr4Oi1HU5w==,type:str]
    pgp:
        - created_at: "2026-05-03T18:42:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ//TPqaPaj6HsHZyIFYgQjGYdVoaGDVGk6IIurSZCYjWqlh
            vy4Ni21brsjOxJd6SAL2jp5fgu8ets/cpRNFuOz6az+6AogynGttxrihbFH+xmX3
            YlFlNzpv3ib3e095ZBFYSYMwFCSrL/zf2Ea+Cg7XcJ2E4BflSJtP2oxIyI0HyCBt
            p/CbH5RZiRczJt507pf0OWBMfpEa+a69VBW+R9LDNkns3gMbq4Ad0GrqS+A8GpM5
            kWoPfmu/+e9jMoaNtQYb+f7/Pb8l8WiGozfsRfvaR2AgdutDOjyo3svtqapGNZJ+
            lVncmca18dat77KJn7B45Ltkh/h+utRt9pNmKneKb2ygSP3u0cfVJa5+81w6ZCq+
            QLuz5bio+Q9w6a+CjrOKBUARbSIX3dRcGqxtR4WiEYvFp0Rrz5f/yLuaolM1ls2I
            yjp5uvUdKsI0AamwkXHMGRvu6cR77ScSzfWhFvFYCTn/PFMvsBu0N0mtZLjLCPr6
            hEtW94LN6dP6yB2zNyKGrolBKApE9PcvUPNVOMSsZuE4g+WYm+ttqalw6bPUyICn
            hE02NpC009rq9lP6ZVmG9HVVWkQbdF3Su8Pc2oCwd0/UbouenIn8zq2Zaj9+REqD
            OAD00nKiCiR6Q15+ERjlGY17N93qsJjK3eeZm3bxJIXflidSv1aag5SIzWL/qdrU
            aAEJAhB3Zn0J/yttG/Dhr4hcadtd2QKiAMEetnS8Hm2PfC7lVKP6Y0Ae5G08Aczc
            h9+F9hvBRUDF10Im6hXR5l4GL8K5VmXwwzU5bbli6pdnoG3IW30OcI3WthjNwT0D
            OBoF9sa3ENp3
            =7PqT
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
