apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - pvc.yaml
  - litellm-db-secret.yaml
  - litellm-masterkey-secret.yaml
  - litellm-proxy-configmap.yaml
  - openclaw-secret.yaml
