apiVersion: ENC[AES256_GCM,data:9nc=,iv:oiV++AG0hyCzGyG0P0PnQyC/87god4wi1ZBXYX4zyHo=,tag:SxlqgWatQqZGP7GH9WuLTg==,type:str]
kind: ENC[AES256_GCM,data:XkenjckN,iv:9Iqc7ssr5FKc/jE6MFaa86z89AZgjdYfHKsK7ZPrEtg=,tag:XVwPN/sDuw3AckRLI3MkSw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rUsd4/3FSUsrl+yV3JUxAEs=,iv:/tg9VRZ0ZYEqtJwHhVCeyorgmsmbA3qTfl5ve1zn1Hw=,tag:/lf6k0BeZxkMetw/UvsP7Q==,type:str]
    namespace: ENC[AES256_GCM,data:w+11,iv:Rs51rwa1m3/+vfklFSR5te3u6Bs1u6YbL0KD62q/sn8=,tag:/M+CYI77ukWn7UCCybCUFw==,type:str]
type: ENC[AES256_GCM,data:qZAUuxDM,iv:90csjHkDwgwV+rf22mPgdFQwc5ZWl4fcEaUzVEaTHpo=,tag:P2XQVMV3G2jOQDw2Vxjdtw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:qryOedzzgRw=,iv:bRIaT17zQL/q9SH8Pb7m7zC8NiT2ULSj5ij4uCwWlJU=,tag:SFCg/X6MzHj0GwanNUg68w==,type:str]
    password: ENC[AES256_GCM,data:Y2UGexI2n64sxy62,iv:NoV3b7JZ+sl6nzbBZrJdrwOsmFl+KWQgU6YNIlIYMmI=,tag:ypwUac3dQNFWjrjCnbt85g==,type:str]
    endpoint: ENC[AES256_GCM,data:PU1fzMTpg6pSOYQlwkPpwlJD+5UQ48/Nv5iaVpHQQ4ln7yfF88I3,iv:gXzHHR/wbowXcwBNCAMR6zxq+uedQb4FQjzfx39Ene8=,tag:e5EE3qb5/XjtXC5yJVFFQg==,type:str]
sops:
    lastmodified: "2026-05-03T18:42:24Z"
    mac: ENC[AES256_GCM,data:qeO+uAZF9VjjTftcDNU8/Huihl9Vtx3O57UBdQ3s3hcgNqQKWLdc61pP0zvM2hdPkH25fNPC+L1N7OwwaOon9Zgbx2Dh6UYeTRJfJVirJziSRpk4XVdolbhwv8MPb6V3MA6eBknPF8FUta6rU1bkDNhU+hVqiuXhFJWwDrieQRU=,iv:0RPWkoZAkkz4apN+A+4Cpn54du7zR8nwHUSs36jmEfY=,tag:eSAQEIb92YzzoZRPagj4dg==,type:str]
    pgp:
        - created_at: "2026-05-03T18:42:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ/+JHCxnSHyfXVqS/H+tGqWtIm4OFBqgEl5/px8cPhAowcR
            9x9InvoSTYcjh4lebF2TPe2mp/M+dqtJdrTTjm0eYncBC7RLm/GenGeOO02DF8KJ
            IHlRXc7pWRC4duMrA1R1fAYqK+mC8JFp96MHe5Ljlf1u3QJ34p3q16lRzHFANrMt
            +Nd3CHq33o4V1EgjmNoSPq4YmC8rBg3Pc9wZi2a4UzlnLFhgw/9UFqwv3GXQ3t4k
            PGB4hMSdETsh4+du+6BuMIgy61WlNp/bDQYHT0CgpAyGiFlrknWUgtTZj2/h2m+c
            nL5uviSG48pF5ZkDw1pt3VoCBR3HyzF4kSzP4JJX9hgxoRfpKbR5j8zIJbTmirs7
            BgrTQK8UQ4Kyh+CxMHCxSihskqgafFSwBIJrghS3amvMp6zoeWRmpmyXhx52Vf0M
            /J5YYl9uF8/1b0WRX8tTXjgZKu13CmfLiY80e4WJAJBAnNICRQAQRJz+vWK1tBXy
            qqjnq91ZqIaGiAfQOisU9kcsO7fzusG4G7JEMFgi6HH9YbeiTyP9O0Do2ebN21RK
            zNGcmyY1aGW3OK3rk1pxkycVWhBW5+8mOosG8lwamlp5R7ivcn4HDsQeXZHxzAnE
            iw3DfM8gCwcImfxXUJElBXP1k31Q0vysMW3Vu4YZD1WAFVoXDeexusq40eGazqDU
            aAEJAhCGG/ml6uMWBoWH1M7AvFbkt+Fnv6Z1UCw3QNzUn0Vh5bzRT8wBCXebsqqz
            JhZ9UG6XDgqmbAobauEWYb7X4Hpy942XCvgkc/O2fiE8sU9uetIuSDBeNgrQJZH2
            PsYQ10XOh1ix
            =QS+w
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
