apiVersion: ENC[AES256_GCM,data:U5k=,iv:Jvj32Z1eRp5ZalYtu+3leuFFs89b6qoObLL8R6yg5Fo=,tag:rqD1S7RgHZAPy/NGbIr/PQ==,type:str]
kind: ENC[AES256_GCM,data:LBvfXdi7,iv:boDWMQgmY4LqK98Li2JrgaOZ6ESFYAxTtCyFPMWl7ns=,tag:+AHopQI0IEcQns134vlShQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iXbZABiLAxPdBNoRbNBj0pc=,iv:whFm9zxqZbPnc80gxYT5tbbh7GYokA4YcnyzcpGXizM=,tag:IGu/DIREwLRZN4TCBFn+vw==,type:str]
    namespace: ENC[AES256_GCM,data:0SHW,iv:EhWWOdP5AIO/A6izuO3Iq6G/ZBXgvjyzWMZ6r+9x5Pc=,tag:klHjGLJ9IBKpWBeL9RBckQ==,type:str]
type: ENC[AES256_GCM,data:xoX9gZKk,iv:pdflCRc94dfvJmhX4DGMlcjgcspbyNLftzb+zLgRnx0=,tag:v2Y+kjzJ9w8OV5AqibumXw==,type:str]
stringData:
    masterkey: ENC[AES256_GCM,data:5MlfQ2PvT8FJ9Qt8,iv:4zjpJAJ4Qj0ULmpRB4XcV4Yibw0WNYGDugRn4P0TduE=,tag:I/aodw6Jx5ag2CUwFxx8kA==,type:str]
sops:
    lastmodified: "2026-05-03T18:42:24Z"
    mac: ENC[AES256_GCM,data:Iz2UKRnN6JQV2xeE2ubxmKdp/HqXoBFmsXHDmp6N5eYQ3C7X2x+AggV4IgWlf5IMLbDpQ+SAAxOSkrDvkAT7g2ajzqee2DmTnm6PbqSNzcHAKTsp1pY1mDpW+/o6LQI2cI6cYftuPtyY6FAFweBpE/7WcJV7TVIpc4jpuUUrsiA=,iv:EWkRYPWpdysNd2mmKxqOv74+P8rOq13bR5H06sIv6JE=,tag:L3FRk9pz9UkIHhBgXL7MNg==,type:str]
    pgp:
        - created_at: "2026-05-03T18:42:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ//a82jAlWkWikDZ87B2UvalriXEoFfg5TjJ8NuOAbB7aOa
            PSPAcA1oNvoGSVZL47F8ziMDTpAkgmzB+BVRge06R1trqeMNjeEwWNo5luk3YCkN
            n8thcQ3ENesUYiugwPUiiZkf5nI99uXqO/LKe0RIwJRV+WPT9JWemq5R5u18uyNw
            4f7Td8fxZwvbKjIq34KgBKPM0NZDq3ZOpqxy4luLUb9frHULOalJLopaWeuGPY77
            bw877Dyh2ABzg4lBTVlorN1VbrrkVqbzAltcWZvykIPwX0LySQxowEQ1eJDvbWrX
            Lav/A/p9ZigL70ldLZHkK23eEEkEjHeLRJcA2LQcsQg/ljPTu3NT9SXk0jpB28Y4
            q21KVqgj/SRwfqk/pjoF/73Gt4qJTHRin4abbvohx5yUjU49LSuD+L+1FMoD4i6M
            L5MKf8fdzINOTrmjZHH7uJSHcVA320x/kt/3D08YX1S7nRa9MIkHO5Yn+jow1Gq7
            j8+wEhcdJ/75YGD5osa4UJ9pBiGuR9oL67WRapv/KZ06jE/eazDvHQDZbp+i6f/J
            9+xgVq4ceK7YXeKgQMOxpz725EMELyV0f/xQkw5mByANzqKE8S1Rg9j7WWtos7IZ
            atC43DA3IMTF/36V+jbgmwBSuvSBcIb6fqi2ZzZu/VVHGksVKePbJCldh085qRXU
            aAEJAhCYSBpynP6SJqVbYRpjJgvvnTehTLGtEliKj4cW31kxkj2a52csOEGqTXnP
            pyvZRd2QoIiwk5TaFxpy+bjYN4CG8W7YygWGd8ldMVxkFN/gI6/AoHBVwCSQbnBQ
            C3Na+49lPRBy
            =Y67X
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
