apiVersion: ENC[AES256_GCM,data:4jk=,iv:uOEhl5zOUN9ZGIdHFME7saqLM5mEoAmMA70JhEGhuTY=,tag:293KIumufEA/d6kTrAgQ5A==,type:str]
kind: ENC[AES256_GCM,data:WmAqBn7B,iv:P1ploFguavGyGYpIYA3/sJ24yZHIbC4pe1d/ws+Lvmo=,tag:YlS7vjLwXwXCqzdjD8spUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xcdpX8WkMthqRT8o6pnB,iv:OQ6GzLTYefbUVEDmR2zfWjQmlq2PwGYDGwZenH6+SSY=,tag:u9GniQy/K9FwGzg1pLYwRw==,type:str]
    namespace: ENC[AES256_GCM,data:YgM9,iv:sEo6PyZDoX3iBDhPvTZlJauT6IBvrxsNpDGCemJ0GzU=,tag:BukwC/NIFhTrkhBRrAW7fw==,type:str]
type: ENC[AES256_GCM,data:9wMfRDn1,iv:QKZjZ0iYSiO0sSe9+i4Tdl/alcwo+RzyG7rKPpj2Dkw=,tag:UZLsJBB7VGsxIw5JTypvzQ==,type:str]
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:cHDnQBxZxlixpoDC,iv:JBnl6rEm/h3o9EsWaNJwkk6PtDX0iX8gPl7dx3lYI2I=,tag:BHfMi4rounTOX/R6TcmiAA==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:ANr3iDlB2mUe60mt,iv:FZojZ+A2jOGXL08eteSG0KfY0qdhJ24tTRk+cYOu8Ag=,tag:sxN/mdve/1OO/nscUb2G9A==,type:str]
sops:
    lastmodified: "2026-05-03T18:42:24Z"
    mac: ENC[AES256_GCM,data:sW58wyPm0C25swHTuFJTI756TULki5hyru326+vD+Pj8GUpR4n0T8qTbUZ2rlHQTd1HHRZ9WtVcQAVmeCSv7oJWLXrZH6UjFu0bjrH3rzUL60qjAXgqDYXprpOV/ordXnS4Bp2zK8GPRXxq6WJyQ+4I1176b7UZnQemTQHns4ZI=,iv:53CJDfau0N2jJqiQOwNYP7su/gzCfVVraBCmLsv/l2s=,tag:WBAvhMsMg+CwisGFGCjuLQ==,type:str]
    pgp:
        - created_at: "2026-05-03T18:42:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ/+PwRydOTEsEa8vioeZo1QP5o3M37HB4vfgsfdRk6xV8kh
            3UOZafDUjeTONJurvpnhQv1QXAVXwLSFyzjrGoInLk6RY8XzEc0L7IYpp/KXQJRE
            7B/R3OBgNbHCOIZ0wFpA3s+WWRBaC1V1VTJDx98eM2/c6aQ5wydPAyC8KIOi8Uob
            OL8qcdT3gVArh47sO++e/lBmxmIYv5O9G41/I6PcjTXWvsJm670AcgtupqjV8cs6
            FD1Ru8Rvz+GJ8uFNw3oNAYVraVljtu+KJlZ4XzfBGBDs6syAdX8SDDRPSdMD/TYP
            D2pKWvZTEmqsOfm8Aelcr3RUoSjr+KGbMA9nxsjEw/FRo4GjZbiMyHIRQz6PK7C8
            PU0dpz0eJj6DNgjBAaPiSVTU6FJOe2jZ7KY/INvzZL13T0V5Fj7ay483kQGBi+u5
            xsfCi20b4K+rVlKI2+8+G4PRj5Uz4HAHgwBAG59mWGaqFeLzitXw9J/9Kiwuz+T4
            Wvkxisr927KOpz3JzifZcBwH7kYbBw2htWBrn+QazSnXdzAua2NmUKsvhn1YTQxD
            jFqwss5WNzZXjMfjI4Y0k6BNXcOZrT5OPehP3Wb5Tb/NYG8/aGARJHdwKJAPfzQu
            JAM3mMBLgeiAuqxhZeMNYPhYWZ3I/mK2yO1hmDMKsKvcKw8pB+DA7FzvUxnKnHTU
            aAEJAhCZWs/eXXJwKvBWpTqsAIVBT223jrFzbjJa4FOg5I8r8c9VYAe5qyBX1PT4
            zgFpux0uxkC4yK7PYpeygVmWgktTNm6LioS9Hw1vVwv5UcY2J1eVzRmt/HXZUa14
            iFwiCJftyh0F
            =JhS8
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
