apiVersion: ENC[AES256_GCM,data:Jwo=,iv:ygJmoKM4IHoeXdrnIzWCUCJOUzkWhTvR5wfOK79l/uw=,tag:mYYu4agYQoOoeHp/MI0csQ==,type:str]
kind: ENC[AES256_GCM,data:qF92zQol,iv:YkEILXbNqFOk46cw43E1hCj8W2suOtwnh37Dbj15GyM=,tag:MRFWmAeBTSX8OH9odpEclA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZzCJDDX1xY6W72g=,iv:izdBsioCpQDW0L6H9YZ++JEDq5eTeIFSb5skm+J3H8M=,tag:tPrjSUNkauvqP80ipnCK6Q==,type:str]
    namespace: ENC[AES256_GCM,data:mslM,iv:29roqC9UoItjY7ZRy2F7cLBbQa8GF2Oh54LJp4NdI4I=,tag:SWkTDMLU1mC0hh1XEmAO2A==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:3F1+yknkayviuEy0,iv:Si0BfAHbVrnQgdfmoG8FRtiU9cmd7b/rS4/xNjUOqMg=,tag:2PUMd6YauYBExmqRHuBz2A==,type:str]
sops:
    lastmodified: "2026-05-03T19:36:48Z"
    mac: ENC[AES256_GCM,data:IWgYwJnJGE7q28Nkf0TM9NvmgwOMzRIF+vIw1Lxy7QeuLf4uINwoyKC/Ihavd6gdYR0ucCl/7rDbe+pR+Id3F0NUcZEkPc29zUOUrVC63WMXC5q2PUhrdQ90tLNoaacJSUMsXBxA2b+3imK2RFgbzFo6HwMIGJJHP5sMq5gvHOE=,iv:KY1GUKEqz4O6X3uTKNljsKMEgmR1QJXV15groP02CRg=,tag:I1eGOWd5aQx3geVKJYJUYQ==,type:str]
    pgp:
        - created_at: "2026-05-03T19:36:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ/9E2UHKyJF9pvzUoxreKuBpN+wypfFGXq46XLCrqK+UqSW
            5/h2Zf+ssJXqKSwwf/yztppkDYxHqgygHDZgl/EwH2UjBDyiESxPtrT+yqjHLSxc
            ZfTHAPzAvrlOZdM++55458Cmo7Q6GIvLbyWSqnnm0pzRxIfByZZcZQBoaVexV9Lu
            bvTCO1NDt0+77tmYNiDkWMSU18a4kBwzZE/kiFSsk0z6IkPk2J4ubfUl9Nv7yHmU
            0V3VLm9ONQFHGeLkEjbZrs8DB3Copj3FrynVhUOmXTG3EhFUcSYIDVaNrwlr5iYg
            jHgsaj7XWKmi98KB6+49KOw3L8OBLXcom4X3tG0fjhUrjtUvz+jxPdwqKO3AXV2R
            QrQr+sR5GH4n4G95x6NCG3GspMEWKOs0P5SNKnmr2DdYag/IQ46alsbxaaObVHtg
            NJh3QLIt/l7AMpwef7eaB85bbS1wMJdgym3Ln7lO0o1fvGp83IeXQ63Wsdaf4Iae
            2cjzCwWhVPI5H0M3aCe245nbQ0gyrIPIP0ghRSBrdaqhPdL0jZBBOiVREo6bQNDa
            zYPAuON0/ljw2emm+dnkGEBNh9QDOzVTAe+FLXF8h6UoRiJ2VHkvYJ4J5y+Xpi2b
            eQWX6kPUTctxI00RtY/8/WD/8VSn1CXeWTpisvMmMppEE4Cc5eoWI8qUuVZxn1PU
            aAEJAhBq+m0ogLYZ1wN0dAr9ta5tyS3tArSBRBxI4sSQaQAmNoxyJXVrwIfY+sN9
            lYQdHZpdSmnnjubBQPa3zUPEFVZxAX1RYg1tX05bPQyMHifAYr85flkGXYUQBBuq
            zTGN8u3o0m26
            =jIMC
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
