image:
  repository: rhasspy/wyoming-piper
  pullPolicy: IfNotPresent
  tag: "1.0.1"
  args: ["--voice", "en_US-joe-medium"]

service:
  type: ClusterIP
  port: 10200

# Optional: node affinity to prefer GPU nodes (uncomment to enable)
# nodeSelector:
#   nvidia.com/gpu: "true"


resources:
  requests:
    cpu: "10m"
    memory: "64Mi"

persistence:
  data:
    enabled: true
    existingClaim: llm-piper-joe-wyoming-piper-data

livenessProbe:
  exec: null
  httpGet: null
  tcpSocket:
    port: 10200
  initialDelaySeconds: 30
readinessProbe:
  exec: null
  httpGet: null
  tcpSocket:
    port: 10200
  initialDelaySeconds: 15
