---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: nextcloud-data-pv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  claimRef:
    name: nextcloud-pvc
    namespace: nextcloud
  mountOptions:
    - hard
    - nfsvers=4.1
    - intr
    - timeo=600
    - retrans=2
  nfs:
    path: /nfs/kube/data/nextcloud/nextcloud-pvc
    server: REPLACE_WITH_NFS_SERVER_2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: data-pv
  resources:
    requests:
      storage: 5Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Ti
  volumeMode: Filesystem
  claimRef:
    name: data-pvc
    namespace: nextcloud
  mountOptions:
    - hard
    - nfsvers=4.1
    - intr
    - timeo=600
    - retrans=2
  nfs:
    path: /nfs/kube/data/nextcloud/data-pv
    server: REPLACE_WITH_NFS_SERVER_2
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-pvc
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: photoprism-pv
  resources:
    requests:
      storage: 1.1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-pv
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1.1Ti
  volumeMode: Filesystem
  claimRef:
    name: photoprism-pvc
    namespace: nextcloud
  mountOptions:
    - hard
    - nfsvers=4.1
    - intr
    - timeo=600
    - retrans=2
  nfs:
    path: /nfs/kube/data/photoprism
    server: REPLACE_WITH_NFS_SERVER_2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-2-pvc
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: photoprism-2-pv
  resources:
    requests:
      storage: 1.1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-2-pv
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1.1Ti
  volumeMode: Filesystem
  claimRef:
    name: photoprism-2-pvc
    namespace: nextcloud
  mountOptions:
    - hard
    - nfsvers=4.1
    - intr
    - timeo=600
    - retrans=2
  nfs:
    path: /nfs/kube/data/photoprism-2
    server: REPLACE_WITH_NFS_SERVER_2


