---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  namespace: homeassistant
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: homeassistant-data-pv
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-data-pv
  namespace: homeassistant
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  claimRef:
    name: homeassistant-config
    namespace: homeassistant
  mountOptions:
    - hard
    - timeo=30
    - retrans=3
    - vers=4.2
    - lookupcache=none
    - noac
    - noatime
  nfs:
    path: /nfs/data/homeassistant
    server: REPLACE_WITH_NFS_SERVER
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicassistant-config
  namespace: homeassistant
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: musicassistant-data-pv
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: musicassistant-data-pv
  namespace: homeassistant
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  claimRef:
    name: musicassistant-config
    namespace: homeassistant
  mountOptions:
    - hard
    - timeo=30
    - retrans=3
    - vers=4.2
    - lookupcache=none
    - noac
    - noatime
  nfs:
    path: /nfs/data/musicassistant
    server: REPLACE_WITH_NFS_SERVER
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: popllama-pv
  namespace: homeassistant
spec:
  storageClassName: "nfs-omv"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Ti
  volumeMode: Filesystem
  claimRef:
    name: ollama
    namespace: homeassistant
  hostPath:
    path: "/nfs/data/llm/webui"
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /nfs/kube/llm
  #   server: REPLACE_WITH_NFS_SERVER_2