serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator for blackbox-exporter itself
  ##
  enabled: true
  selfMonitor:
    enabled: true
  prometheusRule:
    enabled: true
  podMonitoring:
    enabled: true
    selfMonitor:
      enabled: true