---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wireguard-system-metrics
  namespace: wireguard-system
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: wireguard
  endpoints:
  - port: metrics