apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: jenkins-data-pv
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data-pv
  namespace: jenkins
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  claimRef:
    name: jenkins-data-pvc
    namespace: jenkins
  mountOptions:
    - hard
    - nfsvers=4.1
    - timeo=600
    - retrans=2
    - nolock
  nfs:
    path: /nfs/data/jenkins
    server: REPLACE_WITH_NFS_SERVER
