apiVersion: ENC[AES256_GCM,data:eGY=,iv:bCHc8oNHlK0gopwlemuQydQ+iHyJTHRL8o78bsDkm9w=,tag:Z3zawfFWYFCg5FcpKkSLnQ==,type:str]
kind: ENC[AES256_GCM,data:Sf3rX5ey,iv:53MG7FsBvmT8ew4a4urr2LbwE5jgTKc4BaOxNtqQO/M=,tag:j1ZJwWN9r+R2wc6eRLHpAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TZLrAWeM5l3DgMeLV842,iv:MkFjQ4iZJoMkUzFLZm6EVGGtTn0YjnjOuNJH9VxjJEI=,tag:TaZ1vlxWoO3UaoQCAKTSYQ==,type:str]
    namespace: ENC[AES256_GCM,data:GbT7IQeQCQ==,iv:8kEgLPkxR1OBVo17QQr3vKUXM7IDZKrGX3ZwrvHdyFQ=,tag:QCIq/kvYCBKf7gEX6fvnOQ==,type:str]
stringData:
    adminPassword: ENC[AES256_GCM,data:LQMWDzAPq9QdpQM6,iv:khN65JwUtmSOO48GrU4HxGXxzdCbRwI1WjACa9tPc1E=,tag:rnoHWLoMk0aAAznxMRNyYQ==,type:str]
    apiToken: ENC[AES256_GCM,data:TPbq3USU5DRDsPkC,iv:6SqiHFuUfVPe+eUYeEjNk7WB2lil6X7zowig3gsFGiE=,tag:IhPhGDiqDhvxFg7EYNK9MA==,type:str]
sops:
    lastmodified: "2026-05-03T18:35:46Z"
    mac: ENC[AES256_GCM,data:z2v7LnrnT9m4u3nWBavR7UxT0aet74omz4WSzkRKSw3LpkQDovbfJZoenENevkathBaMLXZyMFQdAl/I5p2AsJ3SEj2pdMeQ5ApUyoMNJpfm7yGZDCTAlDY16FrQzGZo+M2pIKM0e8ibQeDnLY2DH2qZqmPSs8pi51EKnsXuomc=,iv:C5UnPjEz7DUqsmnnRDn4oOh8taluz9urZo+f320r9t8=,tag:BE3hsYWu3I9K/0yngllB9g==,type:str]
    pgp:
        - created_at: "2026-05-03T18:35:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7ARAAiSlK7YZwQLF429TJYEp2VC9RTqV7Tn8+eDqESeVN+HeJ
            2/Upw3o1yIPAxUDlJkAawXScTallrInnWb4FnR35N7v2bv7hkIRvELzYcINTVefc
            biTGBIy0YgDXsDih4iusuvENRc2iZvP1kD8FNpWYUBjZAf6c5ppvxRsdv+mlqLDz
            ycsQN9PbkFLOSvjoB0IxWyevPmqCk/x0EkjF3zWCatPqfdNUPWCwMFyleaAd+6IA
            BvMMf1k9IgCUVZLo1kUjGJxTcO/6kajG2R0sfvcvm3Qz4IWBKwgmhWHqUdz3Usym
            Ks03iVfXtJOJrNCjc3lnv1/VEpoqk47ca22p7Q22K2S6c+WEjyypDd40fmd43TX2
            6AcCgMlXJriMAUwnu2nqtLRk2eZLZugjkID0QWSIVZttTq4U2WJWQ3uC8Dd2BLfl
            tY3pn4nY7IFWS/74GIQJ2DC5KjNwjeXRbYuSjXdwo8iCcAw4FBvSOgVGvuexmTo5
            EdXp7ArNI3LqoWC2xucA++unWjLi9p/b6A1FQMVtzBMBnuSLZroH/gIFyz+8biQG
            jF5glYJ/Bag6xQT7t3LwFEP4DYWK9wtTY4DI5HlqA1l2MMTz2RZznVbn9k7iLlDu
            4UMhBiVfTE6sjMYiIVERmP+6QZK/SBgFgwu9rdeWTl4ED6o0LaQICKR/RZyjMNrU
            aAEJAhAGKBRBOcXIXc8EAO0RsVU8YMffOKV6kmuAI7vJl5ZOo73jFJZIZQaS1lB5
            GqWR7VaaySbo6meNT1gKsmE3Gl8i92cP+OQld5RASJlI+vGXP9Eh17YpvDrDrPYw
            RPAbmf19S0tu
            =6SGC
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
