apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: registry-data-pv
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-data-pv
  namespace: registry
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  claimRef:
    name: registry-data-pvc
    namespace: registry
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/iso/docker
    server: REPLACE_WITH_NFS_SERVER_2
