apiVersion: ENC[AES256_GCM,data:F6A=,iv:qM99fJYQ4J3xWZitSPepBB8EXjAKO7aUZtrcu8uWaBw=,tag:ReLrMGaotf9VAkH5N+VQVw==,type:str]
kind: ENC[AES256_GCM,data:5yNBsMto,iv:ib4yLiq5YNN+zVadOKJ9lBANA2tftYTR+63eLty09RU=,tag:tMVszdTA9354SrPPO/EN+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UrwVNWj3Zpn03Ylkzg==,iv:WPSDL65HRSZYduxJu/lsRSIS6aMnSFwG26h/AyfjHFo=,tag:NfXM+BcNVVOQqsLQmrv6KQ==,type:str]
    namespace: ENC[AES256_GCM,data:YZ7wz+VMnhE=,iv:XcJMoKNZDLVNA9GdFkySUJfqoiSvcqsyPhFzGFa+U2U=,tag:JNNHT+rHYmikeFHKtGkZPg==,type:str]
stringData:
    htpasswd: ENC[AES256_GCM,data:AEhNd97PQCp1umuR,iv:W3LlySz7/+pz7M1sjSPf96O8pgptUyc5qhJDziVvbFs=,tag:q85R6cmIKXS/67PafCQYsQ==,type:str]
sops:
    lastmodified: "2026-05-03T18:35:22Z"
    mac: ENC[AES256_GCM,data:U/6bpkk1k9wtnkKJbA99qMe0TeWkWQq4PQGCdw5WwHKUrKUZhKd8H7qyOKTWskfE/TSbIgo/QUv6HBMB5AGTzGIpAYYPqNPJQuU1kMkSu8uFMUTtr2R0bROdAuz7UN7a+cFJ49AcXs+l+324NMujCalcVy2wfiJbe1vI7fheFA0=,iv:dljOijty6kBsjfnxTLC/7/y7wblb0y2ed35v6Y0SgUw=,tag:VlLZeTYVtApgDeNxP8UVTA==,type:str]
    pgp:
        - created_at: "2026-05-03T18:35:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ//SLwUMZ9WPPnyqd+DOlO+cvq77tMLwBb7401/YDKPHANI
            Xvne4H3kyiR8LWeRLWPdcIMMxid2r1QWq6sNcpSl2md1avxQzm4TY9pXq6rI3QkB
            hBJW17YXXo+3ap9eZUlxmdi4I3W3XvVfqCgHq+vz+5UNWnRT9o5hcybAhG1cMRAz
            hHP1MX+UXVIHJjRySxGq2dzxjqH6g9lxCm3ijbuiqF0cu1vwccjD7KUFtFZ058/b
            1ROILJ2HfTVdmxD/PM1rkkIv8uGmZ4w2SyxGgF4GwbjOX3cxfGeenatXZ5pTa+xl
            NZMnupcJjIPnogmAIK9AiFuLDkS23rvXlhXB29Q/2a7EGLAtuAs55O/SQyhjkcwB
            7Qdto/PzN4gdUQbyChOFx6UYgK5qFUQnrEP6/yaaRvUzN7PDwsu0sF2O3rePiSPk
            FLd1xzXQ5Usi5dT7Xv2FEKcLju5DBWW6n+/bJ40TU2Tq9GpbcMUB/zvaEk/REkr0
            c02QKfhLR2SxTBwcehzU9QKhM92PtomP9fVbc1jWDYahiyqMtMcUyQXJMjBZx75q
            VnHa4kE2pu8cSuogGfF7BV9d99wdH6eLf2bFHVYwVKOd3/2j79dCpc3sMxXzql3c
            bHtHevWJVDiBRX//1KhRugLI98mSBCtYT29VT1sae5LGl8mFfvuybCR7Fh4rG8vU
            aAEJAhCzVAji8BE4fdyrxHWwQXOO9aEaaPFiudhlFrBuxYOW/dC+AN6QFhF2EF2/
            DzMzoAJW5f/aph8QiMMBQR872tmIs4INpXMOKisFe8KlhenBsWVYXdqcQWYl2AFa
            JoXoQ2ZzB1c/
            =ZUSB
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:CU4=,iv:xMaGDOACZJfD5YwmZgABStB895V/LsDtPoJSOaCOTdM=,tag:19Kv5WhLvOP2NCEEL2YaRg==,type:str]
kind: ENC[AES256_GCM,data:E7gz8ru/,iv:uftF2gb4FsKQYndR0VYiiBao/NGMJFT21jj/j1+MztI=,tag:YZTQhsSwV6Pk9ofTSeS9iw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ek34M+bKbLZTUy5Nmw==,iv:T8XP677ii2x587L9mGmypbyFMIYaRWao45KZvk/P6ec=,tag:k3GeN3WhDNGy3+8xtWPoDg==,type:str]
    namespace: ENC[AES256_GCM,data:E0fiKEEazQ4=,iv:/hNl9DQa63/eLn8Q+hhK0HjvSdy+H9RfL8yCnQUgLXc=,tag:bNIQp93dacINkoUTo3QpqA==,type:str]
stringData:
    registry.crt: ENC[AES256_GCM,data:BEVo2KLm5z7Y8o0/,iv:nlGhrlzpcCa1L5A3/ZB4bmotMuYCfTetskxfVanT+CA=,tag:cjOrmsqhwJ/0cs4K2o4svQ==,type:str]
    registry.key: ENC[AES256_GCM,data:139ugCtsm7FGm0If,iv:lBVfFhWRz1EBn83G2WwgmJ7A6caMCaLnlSKyF9d5roM=,tag:jd7iNkCrgm01sTJoVR7GsA==,type:str]
sops:
    lastmodified: "2026-05-03T18:35:22Z"
    mac: ENC[AES256_GCM,data:U/6bpkk1k9wtnkKJbA99qMe0TeWkWQq4PQGCdw5WwHKUrKUZhKd8H7qyOKTWskfE/TSbIgo/QUv6HBMB5AGTzGIpAYYPqNPJQuU1kMkSu8uFMUTtr2R0bROdAuz7UN7a+cFJ49AcXs+l+324NMujCalcVy2wfiJbe1vI7fheFA0=,iv:dljOijty6kBsjfnxTLC/7/y7wblb0y2ed35v6Y0SgUw=,tag:VlLZeTYVtApgDeNxP8UVTA==,type:str]
    pgp:
        - created_at: "2026-05-03T18:35:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+gdQJpQoZk7AQ//SLwUMZ9WPPnyqd+DOlO+cvq77tMLwBb7401/YDKPHANI
            Xvne4H3kyiR8LWeRLWPdcIMMxid2r1QWq6sNcpSl2md1avxQzm4TY9pXq6rI3QkB
            hBJW17YXXo+3ap9eZUlxmdi4I3W3XvVfqCgHq+vz+5UNWnRT9o5hcybAhG1cMRAz
            hHP1MX+UXVIHJjRySxGq2dzxjqH6g9lxCm3ijbuiqF0cu1vwccjD7KUFtFZ058/b
            1ROILJ2HfTVdmxD/PM1rkkIv8uGmZ4w2SyxGgF4GwbjOX3cxfGeenatXZ5pTa+xl
            NZMnupcJjIPnogmAIK9AiFuLDkS23rvXlhXB29Q/2a7EGLAtuAs55O/SQyhjkcwB
            7Qdto/PzN4gdUQbyChOFx6UYgK5qFUQnrEP6/yaaRvUzN7PDwsu0sF2O3rePiSPk
            FLd1xzXQ5Usi5dT7Xv2FEKcLju5DBWW6n+/bJ40TU2Tq9GpbcMUB/zvaEk/REkr0
            c02QKfhLR2SxTBwcehzU9QKhM92PtomP9fVbc1jWDYahiyqMtMcUyQXJMjBZx75q
            VnHa4kE2pu8cSuogGfF7BV9d99wdH6eLf2bFHVYwVKOd3/2j79dCpc3sMxXzql3c
            bHtHevWJVDiBRX//1KhRugLI98mSBCtYT29VT1sae5LGl8mFfvuybCR7Fh4rG8vU
            aAEJAhCzVAji8BE4fdyrxHWwQXOO9aEaaPFiudhlFrBuxYOW/dC+AN6QFhF2EF2/
            DzMzoAJW5f/aph8QiMMBQR872tmIs4INpXMOKisFe8KlhenBsWVYXdqcQWYl2AFa
            JoXoQ2ZzB1c/
            =ZUSB
            -----END PGP MESSAGE-----
          fp: F81E8088C755BB28
    unencrypted_suffix: _unencrypted
    version: 3.12.2
