apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data-pvc
  namespace: pihole
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: pihole-data-pv
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-data-pv
  namespace: pihole
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  claimRef:
    name: pihole-data-pvc
    namespace: pihole
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/data/pihole
    server: REPLACE_WITH_NFS_SERVER
