ingress:
  ## Enable Ingress.
  ##
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - pushgateway.REPLACE_WITH_YOUR_DOMAIN
  tls:
    - secretName: pushgateway-tls
      hosts:
        - pushgateway.REPLACE_WITH_YOUR_DOMAIN
service:
  type: ClusterIP
serviceMonitor:
  enabled: true
  namespace: prometheus